---
- hosts: all
  become: true
  tasks: 
        - name: install https
          apt:
                  name: "{{packages}}"
                  state: present
                  update_cache: yes
          vars:
                  packages:
                          - apt-transport-https
                          - ca-certificates
                          - curl
                          - gnupg-agent
                          - software-properties-common

        - name: add apt singing Key for Docker :)
          apt_key:
                  url: https://download.docker.com/linux/ubuntu/gpg
                  state: present

        - name: add repo
          apt_repository:
                  repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
                  state: present

        - name: install docker i dependecies
          apt:
                  name: "{{packages}}"
                  state: present
                  update_cache: yes
          vars: 
           packages:
                   - docker-ce
                   - docker-ce-cli
                   - containerd.io
           notify:
                   - docker status

        - name: add usr ubuntu to group
          user:
                  name: ubuntu
                  group: docker

                  #        - name: Remove SWAp
                  #          mount:
                  #                  name: "{{item}}"
                  #                  fstype: swap
                  #                  state: absent
                  #                  with_items:
                  #                          - swap
                  #                          - none
                  #
                  #        - name: Disable swap
                  #          command: swapoff -a
                  #          when: ansible_swaptotal_mb > 0

